# Generated by Django 5.1.3 on 2024-12-02 10:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='txt_az',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Haqqımızda məlumat'),
        ),
        migrations.AddField(
            model_name='about',
            name='txt_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Haqqımızda məlumat'),
        ),
        migrations.AddField(
            model_name='about',
            name='txt_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Haqqımızda məlumat'),
        ),
    ]
