# Generated by Django 5.1.3 on 2024-12-11 02:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='txt_az',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Əlaqə məlumatları'),
        ),
        migrations.AddField(
            model_name='contact',
            name='txt_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Əlaqə məlumatları'),
        ),
        migrations.AddField(
            model_name='contact',
            name='txt_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Əlaqə məlumatları'),
        ),
    ]
