# Generated by Django 5.1.3 on 2024-12-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contact_txt_az_contact_txt_en_contact_txt_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
                ('img', models.URLField(default='', verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'Kover şəkil',
                'verbose_name_plural': 'Kover şəkillər',
            },
        ),
    ]
