# Generated by Django 5.1.3 on 2024-12-14 01:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_coverimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverimages',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarix'),
        ),
    ]
