# Generated by Django 5.1.3 on 2024-11-22 13:33

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ad')),
                ('name_az', models.CharField(max_length=200, null=True, unique=True, verbose_name='Ad')),
                ('name_en', models.CharField(max_length=200, null=True, unique=True, verbose_name='Ad')),
                ('name_ru', models.CharField(max_length=200, null=True, unique=True, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Brend',
                'verbose_name_plural': 'Brendlər',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ad')),
                ('name_az', models.CharField(max_length=200, null=True, unique=True, verbose_name='Ad')),
                ('name_en', models.CharField(max_length=200, null=True, unique=True, verbose_name='Ad')),
                ('name_ru', models.CharField(max_length=200, null=True, unique=True, verbose_name='Ad')),
                ('icon', models.URLField(blank=True, default='', null=True, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Katiqoriya',
                'verbose_name_plural': 'Katiqoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Məhsulun adı')),
                ('name_az', models.CharField(max_length=200, null=True, unique=True, verbose_name='Məhsulun adı')),
                ('name_en', models.CharField(max_length=200, null=True, unique=True, verbose_name='Məhsulun adı')),
                ('name_ru', models.CharField(max_length=200, null=True, unique=True, verbose_name='Məhsulun adı')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Anbara daxil olma Tarixi')),
                ('img', models.URLField(blank=True, default='', null=True, verbose_name='Məhulun görüntüsü')),
                ('desc', ckeditor.fields.RichTextField(default='', verbose_name='Məhsul haqqında')),
                ('desc_az', ckeditor.fields.RichTextField(default='', null=True, verbose_name='Məhsul haqqında')),
                ('desc_en', ckeditor.fields.RichTextField(default='', null=True, verbose_name='Məhsul haqqında')),
                ('desc_ru', ckeditor.fields.RichTextField(default='', null=True, verbose_name='Məhsul haqqında')),
                ('mini_desc', ckeditor.fields.RichTextField(default='', verbose_name='Məzmun')),
                ('slug', models.SlugField(blank=True, default='products', max_length=255, null=True, verbose_name='URL')),
                ('brand', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.brands', verbose_name='Brend')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.categories', verbose_name='Katiqoriya')),
            ],
            options={
                'verbose_name': 'Məhsul',
                'verbose_name_plural': 'Məhsullar',
            },
        ),
    ]
