# Generated by Django 5.1.3 on 2024-11-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Məhsulun adı'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name_az',
            field=models.CharField(max_length=200, null=True, verbose_name='Məhsulun adı'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Məhsulun adı'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Məhsulun adı'),
        ),
    ]
