# Generated by Django 5.1.3 on 2024-11-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_name_alter_products_name_az_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Məhsulun adı'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name_az',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Məhsulun adı'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name_en',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Məhsulun adı'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Məhsulun adı'),
        ),
    ]
