# Generated by Django 5.1.3 on 2024-12-02 01:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_id_alter_products_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='mini_desc_az',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='products',
            name='mini_desc_en',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='products',
            name='mini_desc_ru',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='Məzmun'),
        ),
    ]
